export const examples = [
  {
    group: "Start here",
    id: "plain-document",
    label: "Plain document",
    kind: "file",
    path: "../../examples/playground/01-plain-document.nodx",
  },
  {
    group: "Start here",
    id: "inline-formatting",
    label: "Inline formatting",
    kind: "file",
    path: "../../examples/playground/02-inline-formatting.nodx",
  },
  {
    group: "Start here",
    id: "variables",
    label: "Variables",
    kind: "file",
    path: "../../examples/playground/03-variables.nodx",
  },
  {
    group: "Styles and themes",
    id: "shared-styles",
    label: "Shared styles",
    kind: "file",
    path: "../../examples/playground/04-shared-styles.nodx",
  },
  {
    group: "Styles and themes",
    id: "custom-theme",
    label: "Custom theme tokens",
    kind: "file",
    path: "../../examples/playground/05-custom-theme.nodx",
  },
  {
    group: "Styles and themes",
    id: "docs-theme",
    label: "Docs theme",
    kind: "file",
    path: "../../examples/playground/06-docs-theme.nodx",
  },
  {
    group: "Quick syntax",
    id: "quick-syntax",
    label: "Marks, layout, backgrounds",
    kind: "file",
    path: "../../examples/playground/14-quick-syntax.nodx",
  },
  {
    group: "Document structure",
    id: "rich-blocks",
    label: "Tables and forms",
    kind: "file",
    path: "../../examples/playground/07-tables-and-forms.nodx",
  },
  {
    group: "Document structure",
    id: "long-document",
    label: "Long document",
    kind: "file",
    path: "../../examples/playground/08-long-document.nodx",
  },
  {
    group: "Document structure",
    id: "chinese-japanese",
    label: "Chinese and Japanese",
    kind: "file",
    path: "../../examples/playground/09-chinese-japanese.nodx",
  },
  {
    group: "Document structure",
    id: "arabic-rtl",
    label: "Arabic RTL",
    kind: "file",
    path: "../../examples/playground/10-arabic-rtl.nodx",
  },
  {
    group: "Integration",
    id: "remote-assets",
    label: "Remote assets",
    kind: "file",
    path: "../../examples/playground/15-remote-assets.nodx",
  },
  {
    group: "Integration",
    id: "light-integrity",
    label: "Light integrity header",
    kind: "file",
    path: "../../examples/playground/16-light-integrity.nodx",
  },
  {
    group: "Document structure",
    id: "semantic-callouts",
    label: "Semantic callouts",
    kind: "file",
    path: "../../examples/playground/17-semantic-callouts.nodx",
  },
  {
    group: "Integration",
    id: "remote-styles",
    label: "Remote styles",
    kind: "file",
    path: "../../examples/playground/11-remote-styles.nodx",
  },
  {
    group: "Integration",
    id: "remote-components",
    label: "Remote components",
    kind: "file",
    path: "../../examples/playground/12-remote-components.nodx",
  },
  {
    group: "Integration",
    id: "zip-package",
    label: "ZIP package",
    kind: "file",
    path: "../../examples/playground/13-zip-package.nodx",
  },
];

export function findExample(id) {
  return examples.find((example) => example.id === id) ?? examples[0];
}
